start-at-login = true

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
    alt-h =  'focus --boundaries-action wrap-around-the-workspace left'
    alt-j =  'focus --boundaries-action wrap-around-the-workspace down'
    alt-k =  'focus --boundaries-action wrap-around-the-workspace up'
    alt-l =  'focus --boundaries-action wrap-around-the-workspace right'

    alt-comma = 'focus-monitor prev'
    alt-period = 'focus-monitor next'
    alt-shift-comma = 'move-workspace-to-monitor prev'
    alt-shift-period = 'move-workspace-to-monitor next'

    alt-leftSquareBracket = 'layout tiles vertical'
    alt-rightSquareBracket = 'layout v_accordion'

    alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3
    alt-shift-c = 'reload-config'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'facetime'
run = 'layout floating'

# TODO: use sketchybar
# exec-on-workspace-change = ['/bin/bash', '-c',
#   'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
#   'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
# ]
