"$schema" = 'https://starship.rs/config-schema.json'


add_newline = false
format = "$time $directory$git_branch$git_status$direnv$status$cmd_duration> "


[time]
disabled = false
format = '[$time](white)'
time_format = '%I:%M:%S%P'

[directory]
format = "[$path]($style)"
style = "bold bright-white"
repo_root_style = "bold bright-purple"
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 1

[git_branch]
format = "\\([$branch](bold bright-purple)"
[git_status]
format = "[($conflicted$staged$modified$untracked$stashed)]($white)\\)"
conflicted = "[!](bold red)"
staged     = "+"
modified   = "*"
untracked  = "?"
stashed    = "⚑"

[direnv]
disabled = false
format = '[$allowed](bold red)'
allowed_msg = ''
not_allowed_msg = 'D'

[status]
disabled = false
format = " \\[[$status]($style)\\]"

[cmd_duration]
min_time = 3_000 # 3sec
format = ' [$duration](bold yellow)'
show_notifications = true
min_time_to_notify = 60_000 # 1min
notification_timeout = 2_000

# foltz@navi ~/c/dots (main) [1]> git remote -v
